language: python
install: make && pip install tox
script:
- make ci
services:
  - docker
cache: pip

before_install:
  - sudo docker run -p 6363:6363 -it -e 'TERMINUSDB_HTTPS_ENABLED=false' terminusdb/terminusdb-server:dev

jobs:
  include:
  - stage: test
    python: '3.6'
  - stage: test
    python: '3.7'
  - stage: test
    python: '3.8'
  - stage: coverage
    python: '3.6'
    script: coverage
  - stage: deploy
    before_deploy: cd docs && make html && touch build/html/.nojekyll && cd ../
    deploy:
      - provider: pages # deploy on github pages when merge on master
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: docs/build/html
        on:
          branch: master
      - provider: pypi # deploy on pypi when tag
        user: __token__
        password: $PYPI_TOKEN
        on:
          tags: true
        skip_existing: true
